module.exports = {
  language: 'Language',
  autoPrint: 'Auto print checks',
  currency: 'Currency',
  cashier: 'Cashier',
  cart: 'Cart',
  products: 'Products',
  addProduct: 'Add Product',
  settings: 'Settings',
  sale: 'Sale',
  checkText: '{product} - Amount: {amount}',
  amount: 'Amount',
  cancel: 'Cancel',
  confirm: 'Confirm',
  addNewProduct: 'Add New Product',
  productNotFound: 'No products found',
  checkSaveSuccess: 'Sale check {id} saved succesfully',
  // Cart page
  complete: 'Complete & print',
  total: 'Total',
  addProductToCart: 'Add products to cart',
  // Products page
  product: 'Product',
  price: 'Price',
  productDeleteConfirm: 'Selected product will be deleted. This cannot be undone. Would you like to continue?',
  delete: 'Delete',
  productDeleteSuccess: 'Product deleted successfully',
  // Product add page
  add: 'Add',
  productName: 'Product Name',
  productPrice: 'Product Price',
  name: 'Name',
  productAddSuccess: '{product} is successfully added',
  home: 'Cashier',
  priceFieldNotNumber: 'Please enter a valid price',
  // Product edit page
  updateProduct: 'Update Product',
  update: 'Update',
  productUpdateSuccess: 'Product updated successfully',
  // stats page
  stats: 'Stats',
  date: 'Date',
  value: 'Value',
  saleStatsByDate: 'Product Sales by Date'
}
